<?php /** @var Block_Search $this */ ?>
<head>
    <?php $this->getChunk('chunks/_head.phtml') ?>
</head>
<body>
<?php $this->getChunk('chunks/_menu.phtml') ?>
<form class="search" action="<?php echo Core_App::getBaseUrl() ?>search/" method="get">
    <input class="search_query" type="text" name="query">
    <input class="search_submit" type="submit" value="Найти">
</form>
<?php if(isset($_GET['query'])): ?>
<p>Результаты поиска:</p>
<?php if($this->getCountSearch() != 0): ?>
    <p>Найдено: <?php echo $this->getCountSearch() ?></p>
<table class="table">
    <thead>
    <tr>
        <td>Имя файла</td>
        <td>Описание файла</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->getFiles() as $_file): ?>
        <tr>
            <td><a href="<?php echo Core_App::getBaseUrl() ?>viewfile/fileId/<?php echo $_file['id']?>"><?php echo $_file['name']?></a></td>
            <td><?php echo $_file['description']?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php else: ?>
    <p>Извините! По вашему запросу ничего ненайдено...</p>
<?php endif; ?>
<?php endif; ?>
<?php $this->getChunk('chunks/_footer.phtml') ?>
</body>