<?php /** @var Block_User $this */ ?>
<head>
    <?php $this->getChunk('chunks/_head.phtml') ?>
</head>
<body>
<?php $this->getChunk('chunks/_menu.phtml') ?>
<?php $this->getChunk('forms/_form.phtml') ?>
<p>Вы загрузили:</p>
<table class="table">
    <thead>
    <tr>
        <td>Имя файла</td>
        <td>Описание файла</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->getUserFile() as $_file): ?>
        <tr>
            <td><a href="<?php echo Core_App::getBaseUrl() ?>viewfile/fileId/<?php echo $_file['id']?>"><?php echo $_file['name']?></a></td>
            <td><?php echo $_file['description']?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php for($i=0;$i<$this->getPageFile();$i++): ?>
    <a href="<?php echo Core_App::getBaseUrl()?>user/id/<?php echo Core_App::getParams()['id'] ?>/p/<?php echo $i+1 ?>"><?php echo $i+1 ?></a>
<?php endfor; ?>
<?php $this->getChunk('chunks/_footer.phtml') ?>
</body>