<?php /** @var Block_Chunks_Form $this */ ?>
<form class="upload" enctype="multipart/form-data" action="<?php echo Core_App::getBaseUrl() ?>upload/" method="post">
    <fieldset>
        <legend>Выберите фаил и нажмите загрузить</legend>
        <input class="file_upload" type="file" name="fileUpload">
        Име файла:
        <input class="text-input" type="text" name="name">
        Категория файла:
        <select name="category">
            <?php $form = new Block_Chunks_Form() ?>
            <?php foreach($form->getFileCategory() as $_cat): ?>
                <option value="<?php echo $_cat['id']?>"><?php echo $_cat['title'] ?></option>
            <?php endforeach; ?>
        </select> <br/>
        Описание файла:
        <textarea  name="description"></textarea>
        <input type="submit" value="Загрузить">
    </fieldset>
</form>