<hr />
<!-- HotLog -->
<span id="hotlog_counter"></span>
<span id="hotlog_dyn"></span>
<script type="text/javascript">
    var hot_s = document.createElement('script');
    hot_s.type = 'text/javascript'; hot_s.async = true;
    hot_s.src = 'http://js.hotlog.ru/dcounter/2505783.js';
    hot_d = document.getElementById('hotlog_dyn');
    hot_d.appendChild(hot_s);
</script>
<noscript>
    <a href="http://click.hotlog.ru/?2505783" target="_blank"><img
            src="http://hit.hotlog.ru/cgi-bin/hotlog/count?s=2505783&amp;im=307" border="0"
            alt="HotLog"></a>
</noscript>
<!-- /HotLog -->
<!--LiveInternet counter--><script type="text/javascript"><!--
    document.write("<a href='//www.liveinternet.ru/click' "+
        "target=_blank><img src='//counter.yadro.ru/hit?t12.6;r"+
        escape(document.referrer)+((typeof(screen)=="undefined")?"":
        ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
            screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
        ";"+Math.random()+
        "' alt='' title='LiveInternet: number of pageviews for 24 hours,"+
        " of visitors for 24 hours and for today is shown' "+
        "border='0' width='88' height='31'><\/a>")
    //--></script><!--/LiveInternet-->
<!-- begin of Top100 code -->

<script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?3141081"></script>
<noscript>
    <a href="http://top100.rambler.ru/navi/3141081/">
        <img src="http://counter.rambler.ru/top100.cnt?3141081" alt="Rambler's Top100" border="0" />
    </a>

</noscript>
<!-- end of Top100 code -->
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- host-most -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8664222405591769"
     data-ad-slot="5348850335"
     data-ad-format="auto"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>

<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- host-most2 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:320px;height:100px"
     data-ad-client="ca-pub-8664222405591769"
     data-ad-slot="8302316732"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>