<?php
    $seoInfo = new Block_Chunks_Head();
    $info = reset($seoInfo->getSeoInfo());
?>
<title><?php echo $info['title'] ?></title>
<meta name="Description" content="<?php echo $info['description'] ?>">
<meta name="Keywords" content="<?php echo $info['keywords']?>">
<link rel="stylesheet" href="<?php echo Core_App::getBaseUrl().'static/main.css' ?>" />
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo Core_App::getBaseUrl().'static/function.js' ?>"></script>
<script src="https://apis.google.com/js/platform.js" async defer></script>
<meta name="google-signin-client_id" content="1066190701533-8ik93mv099jahiu4b8hcet29bkucojvt.apps.googleusercontent.com">
